#!/bin/bash

gocrpytfs -passfile /tmp/backups.passwd /cipher/backups /backups
gocrpytfs -passfile /tmp/database.passwd /cipher/database /var/urbackup

echo "/backups" > /var/urbackup/backupfolder
chown urbackup:urbackup /backups
chown urbackup:urbackup /var/urbackup
exec urbackupsrv "$@"
